### ISSUE TITLE
Lint OpenApi Spec

### ISSUE THREAD

**Issue by dta-trifork** [trifork/trireg2-api#12]
Suggestion: Lint the open api spec based on a predefined ruleset to enforce an agreed upon standard and validity.

**Comment by dta-trifork** [comment]
I assumed I could submit a PR for this proposal, but sadly I do not have the rights xD

**Comment by hmmtrifork** [comment]
Great suggestion, @dta-trifork  
I have granted you access to the repo now so that you can submit your PR
