### ISSUE TITLE
Maybe change the default BaseURL for the server in the API spec to be something like https://replace.this.with.trireg2.server.URL

### ISSUE THREAD

**Issue by hmmtrifork** [trifork/trireg2-api#28]
Instead of http://0.0.0.0

Solved in https://github.com/trifork/trireg2-api/pull/41

**Comment by dta-trifork** [comment]
Suggestion: Declare an array of the official urls according to the amount of environments. That way consumers of the API won't have to manually, edit the OpenAPI files.

Official documentation: https://swagger.io/docs/specification/api-host-and-base-path/ 

Relevant example: 
<img width="993" alt="image" src="https://github.com/trifork/trireg2-api/assets/71636857/7c9bf090-4d00-4319-9493-6090116c666c">
