### ISSUE TITLE
Add a Github action that zip the OpenAPI spec and puts in in Github Artifacts

### ISSUE THREAD

**Issue by hmmtrifork** [trifork/trireg2-api#5]

**Comment by dta-trifork** [comment]
I would be happy to help with this and any other ci related tasks if you need it. : )

Do you have additional requirements for this one or simply archiving the result on a pipeline upon merge to `main` ?

**Comment by hmmtrifork** [comment]
Thanks @dta-trifork !

I have actually made this PR for this issues
https://github.com/trifork/trireg2-api/pull/10

You are welcome to review it , or if you have any other suggestions on how to publish the OpenAPI as a zip file for easy download, you are very welcome to point us in that direction :)
